# This file was generated by GoReleaser. DO NOT EDIT.
cask "aodv" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "8e98d84cae48929416fb69a4f50a3c73d512ec8c2c56eeff60f99adbe9645419"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-x86_64-apple-darwin.tar.gz"
      rename "aodv-0.2.2-x86_64-apple-darwin/aodv", "aodv"
    end
    on_arm do
      sha256 "1a180189be5174f643e189404889a5ac6d1538b335a58965bc02a082d0029e5f"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-aarch64-apple-darwin.tar.gz"
      rename "aodv-0.2.2-aarch64-apple-darwin/aodv", "aodv"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc94da911ca0d5f7a476543a6f4fffe7b428dea5c0df443ba9d013008bce0855"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "aodv-0.2.2-x86_64-unknown-linux-gnu/aodv", "aodv"
    end
    on_arm do
      sha256 "63abea65f976cff36eec5d5a06084b267a34040b93bb30fd08c18c26f86b869d"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "aodv-0.2.2-aarch64-unknown-linux-gnu/aodv", "aodv"
    end
  end

  name "aodv"
  desc "Userspace AODV control-plane implementation based on RFC 3561"
  homepage "https://github.com/Fierthraix/aodv-rs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aodv"

  # No zap stanza required

end
