# This file was generated by GoReleaser. DO NOT EDIT.
cask "aodv" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "d8b1c03bac311113f738dfdfbfed22764a66369b76be1e128ec01f36cf448d82"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-x86_64-apple-darwin.tar.gz"
      rename "aodv-0.2.2-x86_64-apple-darwin/aodv", "aodv"
    end
    on_arm do
      sha256 "df1dbaa51f75ab9fdca2c0874bb6e0346ec8bda80240b8b5c52998a987fc4275"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-aarch64-apple-darwin.tar.gz"
      rename "aodv-0.2.2-aarch64-apple-darwin/aodv", "aodv"
    end
  end

  on_linux do
    on_intel do
      sha256 "65768f73a438d567bfb45d73138d397a9619b0286a49e265a51cd0e08fd253e2"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "aodv-0.2.2-x86_64-unknown-linux-gnu/aodv", "aodv"
    end
    on_arm do
      sha256 "9c78210f2e7a8d4150bb2e3d4fe9df6dcea150cb37ec46537011d82badb858a5"
      url "https://github.com/Fierthraix/aodv-rs/releases/download/v#{version}/aodv-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "aodv-0.2.2-aarch64-unknown-linux-gnu/aodv", "aodv"
    end
  end

  name "aodv"
  desc "Userspace AODV control-plane implementation based on RFC 3561"
  homepage "https://github.com/Fierthraix/aodv-rs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aodv"

  # No zap stanza required

end
