# This file was generated by GoReleaser. DO NOT EDIT.
cask "klavaro" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "9d1f86b9e053a9fc74e90ce515f1e12545b3a7635b64c217e9138400bcbd212f"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-x86_64-apple-darwin.tar.gz"
      rename "klavaro-1.0.5-x86_64-apple-darwin/klavaro", "klavaro"
    end
    on_arm do
      sha256 "c2b58ed787da27ba045064ab0d565deb0ae9dc23d757c594f7177325abc98d17"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-aarch64-apple-darwin.tar.gz"
      rename "klavaro-1.0.5-aarch64-apple-darwin/klavaro", "klavaro"
    end
  end

  on_linux do
    on_intel do
      sha256 "144da81bfb6e5f5cd22cd5bdc8e957cdb58507b2cd9bacce86397854d1c756da"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "klavaro-1.0.5-x86_64-unknown-linux-gnu/klavaro", "klavaro"
    end
    on_arm do
      sha256 "fda59c3c4e726340e8aed1c514d2f3c96ad64a037ba47c7ef26e6930e1434ceb"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "klavaro-1.0.5-aarch64-unknown-linux-gnu/klavaro", "klavaro"
    end
  end

  name "klavaro"
  desc "Print your current xkb_layout in Sway."
  homepage "https://github.com/Fierthraix/klavaro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klavaro"

  # No zap stanza required

end
