# This file was generated by GoReleaser. DO NOT EDIT.
cask "klavaro" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "56171213918dc3a8567edac3036d2959fbf314c4acbf58200857fff241544f3f"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-x86_64-apple-darwin.tar.gz"
      rename "klavaro-1.0.5-x86_64-apple-darwin/klavaro", "klavaro"
    end
    on_arm do
      sha256 "d3ec4a5a9ee4957a11ce70aedef1e7c74e76bc7476cdf6c666592685a2d3894c"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-aarch64-apple-darwin.tar.gz"
      rename "klavaro-1.0.5-aarch64-apple-darwin/klavaro", "klavaro"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4119535d3069621c2d78899ae45930195e585998ca102adc0398af72e72119b"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "klavaro-1.0.5-x86_64-unknown-linux-gnu/klavaro", "klavaro"
    end
    on_arm do
      sha256 "80cc534293c061c9b782307357803d2048dfab5a7181bdc35e87d618fa708c35"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "klavaro-1.0.5-aarch64-unknown-linux-gnu/klavaro", "klavaro"
    end
  end

  name "klavaro"
  desc "Print your current xkb_layout in Sway."
  homepage "https://github.com/Fierthraix/klavaro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klavaro"

  # No zap stanza required

end
