# This file was generated by GoReleaser. DO NOT EDIT.
cask "klavaro" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "62d7b9ac09fcba7896398c6bec2e9b81bef071ba6748412ae58580cc0b260406"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-x86_64-apple-darwin.tar.gz"
      rename "klavaro-1.0.5-x86_64-apple-darwin/klavaro", "klavaro"
    end
    on_arm do
      sha256 "3c6029e164796856bea9003a6437815487e120d67a6ae5b13f37f04b89aa211e"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-aarch64-apple-darwin.tar.gz"
      rename "klavaro-1.0.5-aarch64-apple-darwin/klavaro", "klavaro"
    end
  end

  on_linux do
    on_intel do
      sha256 "ea8cb36f592bc60b906c7a7bbff63d91cb8b607c73eb4bd536047c2fc86cdf6a"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "klavaro-1.0.5-x86_64-unknown-linux-gnu/klavaro", "klavaro"
    end
    on_arm do
      sha256 "fceb27a6c7ce045380ec006bcce4e79979dfadfa90980d3e04951c8c342bb678"
      url "https://github.com/Fierthraix/klavaro/releases/download/v#{version}/klavaro-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "klavaro-1.0.5-aarch64-unknown-linux-gnu/klavaro", "klavaro"
    end
  end

  name "klavaro"
  desc "Print your current xkb_layout in Sway."
  homepage "https://github.com/Fierthraix/klavaro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klavaro"

  # No zap stanza required

end
