# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingall" do
  version "2.1.5"

  on_macos do
    on_intel do
      sha256 "fab60fb71aa969c8080cb754d94b13bfcc6292d1066ad32e954e8e2d4e14c7ca"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-x86_64-apple-darwin.tar.gz"
      rename "pingall-2.1.5-x86_64-apple-darwin/pingall", "pingall"
    end
    on_arm do
      sha256 "f7e47b48fee5a065013b601752abc41391e857d3e446898c9dc5f62e8c3e4e18"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-aarch64-apple-darwin.tar.gz"
      rename "pingall-2.1.5-aarch64-apple-darwin/pingall", "pingall"
    end
  end

  on_linux do
    on_intel do
      sha256 "06846713e227bbf6c5956c7446873ff4beac7ed9c321eda3fd1367d827a999bb"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "pingall-2.1.5-x86_64-unknown-linux-gnu/pingall", "pingall"
    end
    on_arm do
      sha256 "4a8989ad1c3808cdf8e31f17be13a86b27940cbf3221dd3e7944645c76366e92"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "pingall-2.1.5-aarch64-unknown-linux-gnu/pingall", "pingall"
    end
  end

  name "pingall"
  desc "Ping everything you can reach."
  homepage "https://github.com/Fierthraix/pingall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pingall"

  # No zap stanza required

end
