# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingall" do
  version "2.1.5"

  on_macos do
    on_intel do
      sha256 "cf7ec4eb396430601c4ba5e26f7ed838d41d61948880446e52a3b1b41d74744f"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-x86_64-apple-darwin.tar.gz"
      rename "pingall-2.1.5-x86_64-apple-darwin/pingall", "pingall"
    end
    on_arm do
      sha256 "31dd3ccf78d572904ccfb26e07e2ede6a57cd9a8259c0f6a60d9bb7729e5f111"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-aarch64-apple-darwin.tar.gz"
      rename "pingall-2.1.5-aarch64-apple-darwin/pingall", "pingall"
    end
  end

  on_linux do
    on_intel do
      sha256 "6da1188c7f84c1d28e46f09111b5f4401bc15fb7f1ade0f0936b1e89a73aedfc"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "pingall-2.1.5-x86_64-unknown-linux-gnu/pingall", "pingall"
    end
    on_arm do
      sha256 "251c13c26b322ba6b2ca19cee4d31c2cc39c5f2a89907fa47e09cf2cb2b8ec49"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "pingall-2.1.5-aarch64-unknown-linux-gnu/pingall", "pingall"
    end
  end

  name "pingall"
  desc "Ping everything you can reach."
  homepage "https://github.com/Fierthraix/pingall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pingall"

  # No zap stanza required

end
