# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingall" do
  version "2.1.7"

  on_macos do
    on_intel do
      sha256 "b1e5bc844e8ffc5d62e579ab803bd3dfed941030efc674984227208b47980cf1"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-x86_64-apple-darwin.tar.gz"
      rename "pingall-2.1.7-x86_64-apple-darwin/pingall", "pingall"
    end
    on_arm do
      sha256 "78a1beb4853c1fe0758c9b449cc6a91f1d95ee8424b5e6609584d82ee2673d48"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-aarch64-apple-darwin.tar.gz"
      rename "pingall-2.1.7-aarch64-apple-darwin/pingall", "pingall"
    end
  end

  on_linux do
    on_intel do
      sha256 "503483d38d5cc01ef798197fae38b45d11bb68fe112920840af8aeb3ca669bb1"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "pingall-2.1.7-x86_64-unknown-linux-gnu/pingall", "pingall"
    end
    on_arm do
      sha256 "90e1e815c7c91e8bd136faeb9e78e36b5dd11518fa0aa1ccad63c1c0ccf33ecc"
      url "https://github.com/Fierthraix/pingall/releases/download/v#{version}/pingall-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "pingall-2.1.7-aarch64-unknown-linux-gnu/pingall", "pingall"
    end
  end

  name "pingall"
  desc "Ping everything you can reach."
  homepage "https://github.com/Fierthraix/pingall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pingall"

  # No zap stanza required

end
