# This file was generated by GoReleaser. DO NOT EDIT.
cask "proverbilo" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "2656930fc1b7995889ff655ab2555ae743110376ac13b803c0543d26cc2a2aad"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-x86_64-apple-darwin.tar.gz"
      rename "proverbilo-0.1.9-x86_64-apple-darwin/proverbilo", "proverbilo"
    end
    on_arm do
      sha256 "951e2450af67c686916a0ba80a618ec2be1fdc6d9b3c44e930ca0e24a287a720"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-aarch64-apple-darwin.tar.gz"
      rename "proverbilo-0.1.9-aarch64-apple-darwin/proverbilo", "proverbilo"
    end
  end

  on_linux do
    on_intel do
      sha256 "6b6dc17bc6f8bb7e4fed3ed3e86eb3582f18d50da3850511c27d895ca8c9c21d"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "proverbilo-0.1.9-x86_64-unknown-linux-gnu/proverbilo", "proverbilo"
    end
    on_arm do
      sha256 "7a3730e6d8319c64e82da71f14139545dbb6a49089f22eea2560c15d6775395c"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "proverbilo-0.1.9-aarch64-unknown-linux-gnu/proverbilo", "proverbilo"
    end
  end

  name "proverbilo"
  desc "Programo por montri hazardajn proverbojn en Esperanto."
  homepage "https://github.com/Fierthraix/proverbilo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proverbilo"

  # No zap stanza required

end
