# This file was generated by GoReleaser. DO NOT EDIT.
cask "proverbilo" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "1e873976024f6d5243f84d1d100e8853b38ec0d96dffd533e3024fc1d4e5096d"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-x86_64-apple-darwin.tar.gz"
      rename "proverbilo-0.1.9-x86_64-apple-darwin/proverbilo", "proverbilo"
    end
    on_arm do
      sha256 "4171aa7ac437e83196108995e70e0efd974a5ce9944631e5dc652d933024b83a"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-aarch64-apple-darwin.tar.gz"
      rename "proverbilo-0.1.9-aarch64-apple-darwin/proverbilo", "proverbilo"
    end
  end

  on_linux do
    on_intel do
      sha256 "c38235bec4ff89ec49fbe1765897c612833b236bace7b8f86c765e1fa251047d"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "proverbilo-0.1.9-x86_64-unknown-linux-gnu/proverbilo", "proverbilo"
    end
    on_arm do
      sha256 "499c018c5b88b8025381d425f8ca4373c91bae58d5e04a994b2fa83637adac06"
      url "https://github.com/Fierthraix/proverbilo/releases/download/v#{version}/proverbilo-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "proverbilo-0.1.9-aarch64-unknown-linux-gnu/proverbilo", "proverbilo"
    end
  end

  name "proverbilo"
  desc "Programo por montri hazardajn proverbojn en Esperanto."
  homepage "https://github.com/Fierthraix/proverbilo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proverbilo"

  # No zap stanza required

end
