# This file was generated by GoReleaser. DO NOT EDIT.
cask "rimilo" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "11739eedac5b1f2dc086ab6c829ea9bb955896a6a91c89ff0b5a853117e308be"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-x86_64-apple-darwin.tar.gz"
      rename "rimilo-0.2.8-x86_64-apple-darwin/rimilo", "rimilo"
    end
    on_arm do
      sha256 "f55ca81f4bf25740582f19084a5573d67d124def617845b03b3089297e5383f2"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-aarch64-apple-darwin.tar.gz"
      rename "rimilo-0.2.8-aarch64-apple-darwin/rimilo", "rimilo"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc54ff587c86c3791c6cb0786930d4bd1bee931d408e29fe985c897575362883"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "rimilo-0.2.8-x86_64-unknown-linux-gnu/rimilo", "rimilo"
    end
    on_arm do
      sha256 "3a86a0843634ad8de9240c33761b31615815c6d4dbf3d6fbc0cfc4b929b49ab5"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "rimilo-0.2.8-aarch64-unknown-linux-gnu/rimilo", "rimilo"
    end
  end

  name "rimilo"
  desc "Rapida rimvort-serchilo por Esperanto-angla vortaro."
  homepage "https://github.com/Fierthraix/rimilo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rimilo"

  # No zap stanza required

end
