# This file was generated by GoReleaser. DO NOT EDIT.
cask "rimilo" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "f27829b5c311d94588dc3b16cd49c2452f95a342eee0538243ed509559695d64"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-x86_64-apple-darwin.tar.gz"
      rename "rimilo-0.2.8-x86_64-apple-darwin/rimilo", "rimilo"
    end
    on_arm do
      sha256 "61119d17442f8f38739f0f2e9530c6af06cec9a27ffefad8df3dc8cbffd0bb06"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-aarch64-apple-darwin.tar.gz"
      rename "rimilo-0.2.8-aarch64-apple-darwin/rimilo", "rimilo"
    end
  end

  on_linux do
    on_intel do
      sha256 "cbf42034786342cbd20cf0a368f93be0c8faacff72d638c0d19b6e2c5724bb68"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "rimilo-0.2.8-x86_64-unknown-linux-gnu/rimilo", "rimilo"
    end
    on_arm do
      sha256 "6a8841b587fc07c7d55f906735f02dcf1c5ff1ed5299dd045b00b431fd2ed4bd"
      url "https://github.com/Fierthraix/rimilo/releases/download/v#{version}/rimilo-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "rimilo-0.2.8-aarch64-unknown-linux-gnu/rimilo", "rimilo"
    end
  end

  name "rimilo"
  desc "Rapida rimvort-serchilo por Esperanto-angla vortaro."
  homepage "https://github.com/Fierthraix/rimilo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rimilo"

  # No zap stanza required

end
