# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmatrix" do
  version "2.0.3"

  on_macos do
    on_intel do
      sha256 "575811bcf3c2f3c5ac46c502490272926b155f6c63b809e4d6c4868d7f37133d"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      rename "rmatrix-2.0.3-x86_64-apple-darwin/r-matrix", "r-matrix"
    end
    on_arm do
      sha256 "7d5bf7fff49f61a42df41af3e8db3fbba65f345d6cb124c1c01f638ac00e938b"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      rename "rmatrix-2.0.3-aarch64-apple-darwin/r-matrix", "r-matrix"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f91ca287652d2c3c98ad5f6b20aae28be7bae5bfd64bb23ff1eaee4b279444e"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "rmatrix-2.0.3-x86_64-unknown-linux-gnu/r-matrix", "r-matrix"
    end
    on_arm do
      sha256 "677c71868dfbf0bb7df96385a9477ecc27102dcc4cc91a9adcdeb96df0ba9a5b"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "rmatrix-2.0.3-aarch64-unknown-linux-gnu/r-matrix", "r-matrix"
    end
  end

  name "rmatrix"
  desc "Rust port of cmatrix."
  homepage "https://github.com/Fierthraix/rmatrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "r-matrix"

  # No zap stanza required

end
