# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmatrix" do
  version "2.0.3"

  on_macos do
    on_intel do
      sha256 "e2cbf5f553c670c0108faa49846d4192bc042f1639fb542aa8dace9e4552ec49"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      rename "rmatrix-2.0.3-x86_64-apple-darwin/r-matrix", "r-matrix"
    end
    on_arm do
      sha256 "143c62877f176d53d491fbba744b4eb43a3c51cbf80713a3b6c738aac7b5c18e"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      rename "rmatrix-2.0.3-aarch64-apple-darwin/r-matrix", "r-matrix"
    end
  end

  on_linux do
    on_intel do
      sha256 "fde581cd11fe848e8eabd0b5c3c71a14c5e25af0bf3a41b47b2f027966d0f243"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "rmatrix-2.0.3-x86_64-unknown-linux-gnu/r-matrix", "r-matrix"
    end
    on_arm do
      sha256 "14cf4085a3cd8b16f7813c8085749b6e693d85afc133f85b693cb47afbce2420"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "rmatrix-2.0.3-aarch64-unknown-linux-gnu/r-matrix", "r-matrix"
    end
  end

  name "rmatrix"
  desc "Rust port of cmatrix."
  homepage "https://github.com/Fierthraix/rmatrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "r-matrix"

  # No zap stanza required

end
