# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmatrix" do
  version "2.0.3"

  on_macos do
    on_intel do
      sha256 "d1ac7c0b32a2d97422fe4e1339f08ac45fd279040d14569f5c985d767c2e1b8c"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-apple-darwin.tar.gz"
      rename "rmatrix-2.0.3-x86_64-apple-darwin/r-matrix", "r-matrix"
    end
    on_arm do
      sha256 "8c4afd9b5269eedfbe1fafe7f26c2804828211fafa1af3696c0dc25d9eef14ba"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-apple-darwin.tar.gz"
      rename "rmatrix-2.0.3-aarch64-apple-darwin/r-matrix", "r-matrix"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3b5ee3649300fec9ca38838cf974c446711cf979264711af6a73b4c0eb7a45d"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "rmatrix-2.0.3-x86_64-unknown-linux-gnu/r-matrix", "r-matrix"
    end
    on_arm do
      sha256 "333cbf394a1dbf9ebfddf32af24d254560b29b3fe391eafbf084516a7dd4f682"
      url "https://github.com/Fierthraix/rmatrix/releases/download/v#{version}/rmatrix-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "rmatrix-2.0.3-aarch64-unknown-linux-gnu/r-matrix", "r-matrix"
    end
  end

  name "rmatrix"
  desc "Rust port of cmatrix."
  homepage "https://github.com/Fierthraix/rmatrix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "r-matrix"

  # No zap stanza required

end
