# This file was generated by GoReleaser. DO NOT EDIT.
cask "sehx" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "4630e2d662975b3868a8e9d695f2c5b29a4b416ee87aac8eea8035861ed2fdbc"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-x86_64-apple-darwin.tar.gz"
      rename "sehx-0.1.3-x86_64-apple-darwin/sehx", "sehx"
    end
    on_arm do
      sha256 "62d0007221f7b917ffcc2f03afd9307005a396501301dc3e6c4ed7a824c4d85b"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-aarch64-apple-darwin.tar.gz"
      rename "sehx-0.1.3-aarch64-apple-darwin/sehx", "sehx"
    end
  end

  on_linux do
    on_intel do
      sha256 "80fda507a816d36479ecf2ae4cb842040555a01291e4c57b13391a15a981e66a"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "sehx-0.1.3-x86_64-unknown-linux-gnu/sehx", "sehx"
    end
    on_arm do
      sha256 "7c85a63a32111504fa8c3d4167bbb3e0348e3d23d0b8e80853ecb5a812c45d93"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "sehx-0.1.3-aarch64-unknown-linux-gnu/sehx", "sehx"
    end
  end

  name "sehx"
  desc "SEnsible HeXadecimal, the ASCII-synergetic little-endian hexadecimal format."
  homepage "https://github.com/Fierthraix/sehx-rs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sehx"

  # No zap stanza required

end
