# This file was generated by GoReleaser. DO NOT EDIT.
cask "sehx" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "28caebe0b7f0368ac95624ef1d0ada5ffcc10e42bcff9db3531a957005f7ac96"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-x86_64-apple-darwin.tar.gz"
      rename "sehx-0.1.3-x86_64-apple-darwin/sehx", "sehx"
    end
    on_arm do
      sha256 "fba0a138d8b086417f5b581693a3ed76c7bd4ba76e3ba50e909eab2b89a544fd"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-aarch64-apple-darwin.tar.gz"
      rename "sehx-0.1.3-aarch64-apple-darwin/sehx", "sehx"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2b066700909dfc2ba28688b9a48ddbb4c3263dc0160892055800240437ef433"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "sehx-0.1.3-x86_64-unknown-linux-gnu/sehx", "sehx"
    end
    on_arm do
      sha256 "b0c6e8857751e73d415e693015db19cb21e76479f38fe09b133d2c6b2ab184b9"
      url "https://github.com/Fierthraix/sehx-rs/releases/download/v#{version}/sehx-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "sehx-0.1.3-aarch64-unknown-linux-gnu/sehx", "sehx"
    end
  end

  name "sehx"
  desc "SEnsible HeXadecimal, the ASCII-synergetic little-endian hexadecimal format."
  homepage "https://github.com/Fierthraix/sehx-rs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sehx"

  # No zap stanza required

end
