# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiny-ping" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "ed2b06bc8fab6f15160b04fbc89c3c83477e7a3818236dd93f70a237cff7b48b"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-x86_64-apple-darwin.tar.gz"
      rename "tiny-ping-0.7.1-x86_64-apple-darwin/tiny-ping", "tiny-ping"
    end
    on_arm do
      sha256 "311e4a6be09940eb640eb8d9ed200add38fe64efb9f6f00d3c2f360f2df4ca62"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-aarch64-apple-darwin.tar.gz"
      rename "tiny-ping-0.7.1-aarch64-apple-darwin/tiny-ping", "tiny-ping"
    end
  end

  on_linux do
    on_intel do
      sha256 "20ccd20a443102443fbd85c592174fa6a1b5f8bdf856b3cec928a0c031bd5f9b"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "tiny-ping-0.7.1-x86_64-unknown-linux-gnu/tiny-ping", "tiny-ping"
    end
    on_arm do
      sha256 "ecabe246737d54d05c78e90c363273fe4232bdcc91fcc202c419b74772d485a1"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "tiny-ping-0.7.1-aarch64-unknown-linux-gnu/tiny-ping", "tiny-ping"
    end
  end

  name "tiny-ping"
  desc "Small Asynchronous ICMP library and CLI"
  homepage "https://github.com/Fierthraix/tiny-ping"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiny-ping"

  # No zap stanza required

end
