# This file was generated by GoReleaser. DO NOT EDIT.
cask "tiny-ping" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "e7060f2ee7c6dcc1ab9276bf38e902fe6309d69184fbac49af636d0d2c7932bc"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-x86_64-apple-darwin.tar.gz"
      rename "tiny-ping-0.7.1-x86_64-apple-darwin/tiny-ping", "tiny-ping"
    end
    on_arm do
      sha256 "76865d5903b176c879fc56d049d2412935cf2ebdfd12c0f2c906c2a1d9439df2"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-aarch64-apple-darwin.tar.gz"
      rename "tiny-ping-0.7.1-aarch64-apple-darwin/tiny-ping", "tiny-ping"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ebc392ef96399539727371b922a23a9f120396a17fe54cedfa7707b5c75d235"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      rename "tiny-ping-0.7.1-x86_64-unknown-linux-gnu/tiny-ping", "tiny-ping"
    end
    on_arm do
      sha256 "5a2831df568f6077da1d992e7be80d25b983f5296f57f8f459a8fe606c25607f"
      url "https://github.com/Fierthraix/tiny-ping/releases/download/v#{version}/tiny-ping-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      rename "tiny-ping-0.7.1-aarch64-unknown-linux-gnu/tiny-ping", "tiny-ping"
    end
  end

  name "tiny-ping"
  desc "Small Asynchronous ICMP library and CLI"
  homepage "https://github.com/Fierthraix/tiny-ping"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tiny-ping"

  # No zap stanza required

end
